name: apptuner
description: A Flutter SDK for Apptuner to handle force updates and maintenance mode.
version: 1.0.2
homepage: https://www.apptuner.dev
repository: https://github.com/apptuner/apptuner-flutter-sdk

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  package_info_plus: ^10.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
